# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.cache/wt [current_project]
set_property parent.project_path D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/new/BtcMiner.v
read_vhdl -library xil_defaultlib {
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/shatypes.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/new/uart_tx.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/big_sigma_0.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/big_sigma_1.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/ch.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/little_sigma_0.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/little_sigma_1.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/maj.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/shapipe.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/shapipe_top.vhd
  D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/sources_1/imports/Kodlar/shastage.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files D:/Archive/notes/Ozyegin_MSc/2021-2022_Fall/CS550/Project/BtcMiner/BtcMiner.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top BtcMiner -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef BtcMiner.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file BtcMiner_utilization_synth.rpt -pb BtcMiner_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
